# TypeProf 0.30.1

# lib/tasks/create_a_task.rb
class CreateATask
  @tasks: Array[Task]

  attr_accessor description: String
  attr_accessor key: Integer

  def initialize: (Array[Task], Integer) -> String
  def do: -> Array[Task]
  def add_task: (String) -> nil
end
