# TypeProf 0.30.1

# lib/tasks/edit_task.rb
class EditTask
  @tasks: Array[Task]

  attr_accessor description: String
  attr_accessor key: Integer

  def initialize: (Array[Task], Integer) -> String
  def do: -> Array[Task]
  def edit_task: (Integer, String) -> nil
end
