# frozen_string_literal: true

source "https://rubygems.org"

gem 'sorbet', :group => :development
gem 'sorbet-runtime'
gem 'tapioca', require: false, :group => [:development, :test]
gem "rspec"
gem 'sqlite3'

group :development do
  gem 'pry', '~> 0.15.0'
end